// <auto-generated />
using System;
using Fulogi.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fulogi.DataAccess.Migrations
{
    [DbContext(typeof(FulogiDbContext))]
    [Migration("20260405171000_ConvertToMultiFuelSchema")]
    partial class ConvertToMultiFuelSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Fulogi.DataAccess.Entities.DeliveryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DeliveredAmount")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("StorageId");

                    b.ToTable("Delivery", (string)null);
                });

            modelBuilder.Entity("Fulogi.DataAccess.Entities.FuelRequestItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FuelRequestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuelRequestId");

                    b.ToTable("FuelRequestItem", (string)null);
                });

            modelBuilder.Entity("Fulogi.DataAccess.Entities.FuelRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("FuelRequest", (string)null);
                });

            modelBuilder.Entity("Fulogi.DataAccess.Entities.StationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Station", (string)null);
                });

            modelBuilder.Entity("Fulogi.DataAccess.Entities.StorageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Storage", (string)null);
                });

            modelBuilder.Entity("Fulogi.DataAccess.Entities.StorageFuelItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<int>("FuelType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StorageId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StorageId");

                    b.ToTable("StorageFuelItem", (string)null);
                });

            modelBuilder.Entity("Fulogi.DataAccess.Entities.DeliveryEntity", b =>
                {
                    b.HasOne("Fulogi.DataAccess.Entities.FuelRequestEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fulogi.DataAccess.Entities.StorageEntity", null)
                        .WithMany()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Fulogi.DataAccess.Entities.FuelRequestEntity", b =>
                {
                    b.HasMany("Fulogi.DataAccess.Entities.FuelRequestItemEntity", "Items")
                        .WithOne("FuelRequest")
                        .HasForeignKey("FuelRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fulogi.DataAccess.Entities.StationEntity", null)
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Items");
                });

            modelBuilder.Entity("Fulogi.DataAccess.Entities.FuelRequestItemEntity", b =>
                {
                    b.HasOne("Fulogi.DataAccess.Entities.FuelRequestEntity", "FuelRequest")
                        .WithMany("Items")
                        .HasForeignKey("FuelRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelRequest");
                });

            modelBuilder.Entity("Fulogi.DataAccess.Entities.StorageEntity", b =>
                {
                    b.HasMany("Fulogi.DataAccess.Entities.StorageFuelItemEntity", "FuelItems")
                        .WithOne()
                        .HasForeignKey("StorageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelItems");
                });
#pragma warning restore 612, 618
        }
    }
}
